[build-system]
requires = [
  "setuptools >= 61",
  "setuptools < 72; python_implementation == 'PyPy'", # https://github.com/pypa/distutils/issues/283
  "pybind11 >= 2.12.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "yadt"
version = "0.0.1"
description = "Yet Another Document Translator"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["PDF"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["yadt", "yadt.*"]
namespaces = false
