[project]
name = "yadt"
version = "0.0.1"
description = "Yet Another Document Translator"
license = "AGPL-3.0"
readme = "README.md"
requires-python = ">=3.9,<3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["PDF"]
dependencies = [
    "bitstring>=4.3.0",
    "huggingface-hub>=0.27.0",
    "numpy>=2.0.2",
    "onnx>=1.17.0",
    "onnxruntime>=1.20.1",
    "openai>=1.59.3",
    "opencv-python>=4.10.0.84",
    "pdfminer-six>=20240706",
    "peewee>=3.17.8",
    "pymupdf>=1.25.1",
    "tqdm>=4.67.1",
    "xsdata[cli,lxml,soap]>=24.12",
]

[project.urls]
Homepage = "https://github.com/funstory-ai/yadt"

[project.scripts]
yadt = "yadt.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
